/** @type {Record<string, unknown>} */
export const vi = {
  brand: "DriveGo",
  brandHub: "DriveHub",
  nav: {
    home: "Trang chủ",
    pricing: "Bảng giá",
    docs: "Tài liệu",
    guide: "Hướng dẫn",
    lookup: "Tra cứu",
    register: "Đăng ký",
    login: "Đăng nhập",
    more: "Thêm",
    moreGroupApp: "Ứng dụng",
    history: "Lịch sử",
    exam: "Thi thử",
    theory: "Học lý thuyết",
    schedule: "Lịch thi",
    studentDashboard: "Tổng quan",
    forgotPassword: "Quên mật khẩu",
    upgrade: "Nâng cấp",
    premiumPlan: "Gói Premium",
    profile: "Hồ sơ",
    application: "Nộp hồ sơ",
    studyCalendar: "Lịch học",
    aiChat: "AI Chat",
    notifications: "Thông báo",
    centerRegister: "Đăng ký trung tâm",
    adminDashboard: "Quản trị TT",
    adminStudents: "Học viên",
    adminApplications: "Hồ sơ HV",
    adminApplicationDetail: "Chi tiết hồ sơ",
    adminPayments: "Thanh toán",
    adminSchedules: "Duyệt đăng ký ca thi",
    adminSlots: "Quản lý ca thi",
    adminClassSessions: "Buổi học & điểm danh",
    adminCourses: "Nội dung khóa",
    adminCoursesReadOnly: "Nội dung khóa (xem)",
    adminSiteContent: "Nội dung website",
    adminHealth: "Cấu hình",
    adminCenters: "Trung tâm",
    adminLicenses: "GPLX & hết hạn",
    features: "Tính năng",
    support: "Hỗ trợ",
    courses: "Khóa học",
    exams: "Kỳ thi",
    contact: "Liên hệ",
  },
  common: {
    loading: "Đang tải...",
    viewAll: "Xem tất cả",
    viewDetail: "Xem chi tiết",
    registerNow: "Đăng ký ngay",
    startFree: "Bắt đầu miễn phí",
    viewDemo: "Xem demo",
    send: "Gửi",
    search: "Tìm kiếm",
    confirm: "Xác nhận",
    cancel: "Hủy",
    save: "Lưu",
    edit: "Chỉnh sửa",
    backToLogin: "Quay lại trang đăng nhập",
  },
  footer: {
    tagline:
      "Hệ thống đào tạo và luyện thi bằng lái xe hàng đầu Việt Nam. Giúp bạn tự tin cầm lái.",
    platform: "Nền tảng",
    support: "Hỗ trợ",
    contact: "Liên hệ",
    copyright: "© 2024 DriveGo. Bảo lưu mọi quyền.",
    terms: "Điều khoản sử dụng",
    privacy: "Chính sách bảo mật",
  },
  pages: {
    home: {
      badge: "Nền tảng học lái xe thông minh",
      title: "Nền Tảng Học Lái Xe",
      titleHighlight: "Thế Hệ Mới",
      subtitle:
        "Hệ thống học tập thông minh và quản lý đào tạo lái xe kỹ thuật số tiên tiến nhất. Tối ưu hóa quy trình và nâng cao tỷ lệ đỗ với công nghệ AI.",
      featuresTitle: "Tại sao chọn DriveGo?",
      feature1: "Học mọi lúc mọi nơi",
      feature2: "Đề thi cập nhật",
      feature3: "Phân tích hiệu quả",
      feature4: "Bảo mật tuyệt đối",
    },
    login: {
      title: "Chào mừng trở lại",
      subtitle: "Đăng nhập để tiếp tục quản lý hành trình của bạn",
      email: "Email",
      emailPlaceholder: "nhap@email.com",
      password: "Mật khẩu",
      passwordPlaceholder: "Nhập mật khẩu của bạn",
      remember: "Ghi nhớ đăng nhập",
      forgot: "Quên mật khẩu?",
      submit: "Đăng nhập",
      noAccount: "Bạn chưa có tài khoản?",
      signup: "Đăng ký ngay",
      orContinue: "Hoặc tiếp tục với",
    },
    register: {
      title: "Đăng ký tài khoản",
      subtitle: "Hoàn thành form bên dưới để bắt đầu học cùng DriveGo.",
      tabStudent: "Học viên",
      tabCenter: "Trung tâm đào tạo",
      fullName: "Họ và tên",
      email: "Email",
      password: "Mật khẩu",
      confirmPassword: "Xác nhận mật khẩu",
      submit: "Tạo tài khoản",
      hasAccount: "Đã có tài khoản?",
      login: "Đăng nhập ngay",
    },
    forgotPassword: {
      title: "Quên mật khẩu?",
      subtitle:
        "Đừng lo lắng, chúng tôi sẽ giúp bạn. Nhập email liên kết với tài khoản để nhận liên kết đặt lại mật khẩu.",
      email: "Email",
      submit: "Gửi yêu cầu",
    },
    pricing: {
      title: "Chọn loại bằng",
      titleHighlight: "phù hợp với bạn",
      subtitle: "Gói cực hợp mọi nhu cầu — từ ôn lý thuyết đến khóa B2 trọn gói.",
      popular: "Phổ biến nhất",
      consultTitle: "Bạn cần tư vấn thêm?",
      consultSubtitle: "Để lại số điện thoại, đội ngũ sẽ liên hệ trong 5 phút.",
    },
    docs: {
      title: "Trung tâm",
      titleHighlight: "Tài Liệu & Hướng Dẫn",
      subtitle:
        "Tra cứu quy trình, mẹo học lý thuyết và kinh nghiệm thi sát hạch mới nhất.",
      searchPlaceholder: "Tìm kiếm tài liệu, hướng dẫn...",
      toc: "Mục lục",
      support: "Cần hỗ trợ?",
      supportCta: "Nhắn tin ngay",
      downloadPdf: "Tải PDF hướng dẫn",
      faq: "Câu hỏi thường gặp",
    },
    lookup: {
      title: "Tra cứu thông tin",
      titleHighlight: "nhanh chóng",
      subtitle: "Hệ thống tra cứu kết quả, lịch sát hạch và thông tin học viên theo thời gian thực.",
      placeholder: "Số CCCD / Mã học viên",
      submit: "Tra cứu",
      resultTitle: "Kết quả tra cứu",
      passed: "Đạt kết quả",
    },
    history: {
      title: "Lịch Sử Làm Bài Thi Của Bạn",
      subtitle: "Theo dõi quá trình luyện thi và tối ưu điểm số trước kỳ thi chính thức.",
      totalExams: "Tổng bài thi",
      passRate: "Tỷ lệ đạt",
      bestScore: "Điểm cao nhất",
      reviewHint: "Gợi ý ôn tập",
      startReview: "Bắt đầu ôn tập ngay",
    },
    exam: {
      questionLabel: "Câu",
      timeLeft: "Thời gian còn lại",
      tempResult: "Kết quả tạm tính",
      correct: "Đúng",
      wrong: "Sai",
    },
    schedule: {
      title: "Chọn Lịch Thi",
      titleHighlight: "Phù Hợp Với Bạn",
      subtitle:
        "Hệ thống đăng ký sát hạch lái xe trực tuyến. Nhanh chóng, minh bạch và thuận tiện.",
      slotsTitle: "Ca thi ngày",
      available: "Còn chỗ",
      full: "Đã đầy suất đăng ký",
    },
    studentDashboard: {
      title: "Tổng quan",
      statProgress: "Tiến độ học tập",
      statSessions: "Số buổi học tháng",
      statScore: "Điểm trung bình",
      statStatus: "Trạng thái",
      currentLesson: "Bài học hiện tại",
      continue: "Tiếp tục học",
      reviewTips: "Gợi ý ôn tập",
    },
    theory: {
      title: "Học Lý Thuyết",
      titleHighlight: "Mọi Lúc, Mọi Nơi",
      subtitle: "Hệ thống học thông minh với hơn 600 câu hỏi mới nhất.",
      roadmap: "Lộ trình học tập",
      startNow: "Bắt đầu học ngay",
    },
    profile: {
      title: "Hồ sơ của bạn",
      subtitle: "Quản lý thông tin tài khoản và xem lịch sử học",
      subtitleBasic: "Thông tin cá nhân và giấy phép bạn đang có — tách riêng hồ sơ nộp thi.",
      basicInfo: "Thông tin cơ bản",
      targetClass: "Hạng đang đăng ký học",
      heldLicenses: "Giấy phép đang có",
      heldLicensesHint: "Chọn các hạng GPLX bạn đã được cấp (nếu có).",
      noHeldLicense: "Chưa khai báo giấy phép nào.",
      saved: "Đã lưu hồ sơ cá nhân.",
      examDossierTitle: "Hồ sơ nộp thi sát hạch",
      examDossierDesc:
        "Ảnh 3×4, CCCD, VNeID… theo quy định mới nhất — quản lý tại trang Nộp hồ sơ, không lưu trong mục này.",
      examDossierRequired: "Cần nộp đủ hồ sơ trước khi thi thử và đăng ký ca thi chính thức.",
      changePassword: "Đổi mật khẩu",
      active: "Đang hoạt động",
      recentActivity: "Lịch sử hoạt động gần đây",
    },
    upgrade: {
      title: "Nâng Cấp",
      titleHighlight: "Tài Khoản",
      subtitle: "Mở khóa toàn bộ tính năng Premium: AI, thi không giới hạn, hỗ trợ 24/7.",
      memberTitle: "Gói Premium",
      memberSubtitle: "Tài khoản của bạn đang dùng đầy đủ tính năng trả phí.",
      memberActive: "Đang hoạt động",
      validUntil: "Hiệu lực đến",
      daysLeft: "Còn {days} ngày",
      benefitsTitle: "Quyền lợi đang mở",
      benefitExam: "Thi thử không giới hạn",
      benefitAi: "AI Chat hỗ trợ luật & thi",
      benefitTheory: "Học lý thuyết & lịch thi",
      openAiChat: "Mở AI Chat",
      openExam: "Thi thử ngay",
      renewHint: "Gia hạn thêm khi hết hạn — quay lại trang này để thanh toán.",
      free: "Miễn phí",
      premium: "Premium",
      upgradeNow: "Nâng cấp ngay",
      paymentTitle: "Phương thức thanh toán",
      paySecure: "Thanh toán an toàn",
    },
    notifications: {
      title: "Thông báo",
      subtitle: "Cập nhật những tin tức mới nhất về lộ trình của bạn",
      all: "Tất cả",
      unread: "Chưa đọc",
      important: "Quan trọng",
    },
    centerRegister: {
      title: "Hợp tác Đào tạo",
      subtitle: "Đăng ký trở thành đối tác trung tâm trên hệ sinh thái DriveGo.",
      section1: "Thông tin trung tâm",
      section2: "Người đại diện",
      section3: "Tài khoản đăng nhập",
      submit: "Đăng ký trung tâm",
    },
    adminDashboard: {
      title: "Tổng quan trung tâm",
    },
    aiChat: {
      title: "DriveGo AI",
      newChat: "Trò chuyện mới",
      placeholder: "Hỏi DriveGo về luật và thông tin cho lái xe trẻ",
      send: "Gửi",
    },
    studyCalendar: {
      title: "Lịch Học & Thi",
      eventDetail: "Chi tiết sự kiện",
      upcoming: "Sắp tới",
      checkIn: "Điểm danh ngay",
    },
  },
  consent: {
    theoryTitle: "Xác nhận đăng ký học lý thuyết",
    theoryBullet1: "Cam kết học đủ chương trình lý thuyết theo hạng đã chọn.",
    theoryBullet2: "Thông tin học tập được lưu để theo dõi tiến độ.",
    theoryConfirm: "Tôi xác nhận đăng ký học lý thuyết trên DriveGo.",
    examTitle: "Xác nhận ôn thi & thi thử",
    examBullet1: "Đã đăng ký khóa học hạng đang học trên DriveGo.",
    examBullet2: "Hiểu quy định thi: thời gian, điểm liệt, số lần làm bài.",
    examConfirm: "Tôi xác nhận đủ điều kiện ôn thi và làm bài thi thử.",
    scheduleTitle: "Xác nhận đăng ký ca thi",
    scheduleBullet1: "Hồ sơ sát hạch đã được trung tâm duyệt trên hệ thống.",
    scheduleBullet2: "Có mặt đúng giờ, mang CCCD và giấy tờ theo quy định.",
    scheduleConfirm: "Tôi xác nhận đăng ký ca thi sát hạch này.",
  },
  license: {
    studying: "Hạng đang học",
    studyingNow: "Khóa học",
    ready: "Đã có khóa học",
    comingSoon: "Sắp có nội dung",
    registerChoose: "Chọn hạng bằng muốn học",
    emptyTheoryTitle: "Chưa có lộ trình lý thuyết",
    emptyExamTitle: "Chưa có đề thi thử",
    emptyBody: "Khóa {code} đang được cập nhật. Bạn có thể chuyển sang B2 để học ngay.",
    switchToB2: "Chuyển sang học B2",
    viewProfile: "Xem hồ sơ",
    noSlots: "chưa có lịch",
    examQuestionLabel: "Câu hỏi lý thuyết {code}",
    examAside: "{count} câu — thi thử {code}",
    docsAll: "Tất cả / chung",
    docsForClass: "Hạng {code}",
    docsShared: "Chung",
    docsEmpty: "Chưa có bài viết cho bộ lọc này.",
  },
  application: {
    title: "Nộp hồ sơ sát hạch",
    subtitle: "Hồ sơ thi chính thức (giấy tờ mới nhất) — khác với thông tin cơ bản ở trang Hồ sơ",
    profileNote:
      "Thông tin họ tên, SĐT, GPLX đang có: chỉnh tại Hồ sơ cá nhân. Tại đây chỉ khai báo cho hồ sơ nộp thi và upload ảnh/CCCD.",
    personalSection: "Thông tin cá nhân",
    documentsSection: "Giấy tờ & ảnh",
    documentsHint: "Ảnh/PDF tối đa 5MB. Có thể dùng file mẫu khi thử nghiệm.",
    fullName: "Họ và tên",
    dateOfBirth: "Ngày sinh",
    nationalId: "Số CCCD",
    licenseClass: "Hạng GPLX đăng ký",
    idIssuedAt: "Ngày cấp CCCD",
    idIssuedPlace: "Nơi cấp CCCD",
    address: "Địa chỉ hiện tại",
    permanentAddress: "Địa chỉ thường trú",
    saveDraft: "Lưu nháp",
    submit: "Nộp hồ sơ",
    chooseFile: "Chọn file",
    optional: "tùy chọn",
    notUploaded: "Chưa tải lên",
    uploadedBadge: "Đã tải",
    backToProfile: "← Quay lại hồ sơ",
    submittedAt: "Ngày nộp",
    savedDraft: "Đã lưu nháp hồ sơ.",
    uploaded: "Đã tải file lên.",
    submitted: "Hồ sơ đã được nộp thành công.",
    loadError: "Không tải được hồ sơ.",
    saveError: "Lưu nháp thất bại.",
    uploadError: "Tải file thất bại.",
    submitError: "Nộp hồ sơ thất bại — kiểm tra đủ giấy tờ bắt buộc.",
    proactiveHint:
      "Bạn có thể tự hoàn thiện và nộp hồ sơ khi trạng thái là nháp. Học lý thuyết và thi thử không cần hồ sơ.",
    waitingResubmit:
      "Hồ sơ đã nộp và đang chờ trung tâm xử lý. Chỉnh sửa được khi trung tâm gửi yêu cầu nộp lại (thông báo hoặc email).",
    statusUnknown: "Không xác định",
    status: {
      draft: "Nháp",
      submitted: "Đã nộp",
      reviewing: "Đang duyệt",
      approved: "Đã duyệt",
      rejected: "Từ chối",
    },
    docTypes: {
      photo3x4: "Ảnh 3×4cm nền trắng",
      photo4x6: "Ảnh 4×6cm nền trắng",
      cccdFront: "CCCD mặt trước",
      cccdBack: "CCCD mặt sau",
      vneid: "Ảnh VNeID định danh mức 2",
      gplx: "Giấy phép lái xe (nếu có)",
    },
  },
}
